//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodefu.Assertion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodefu.Assertion.TextMessages", typeof(TextMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias cannot be blank..
        /// </summary>
        public static string AliasCannotBeBlank {
            get {
                return ResourceManager.GetString("AliasCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is not valid, alias can only contain alphanumeric characters..
        /// </summary>
        public static string AliasIsNotValidAliasCanOnlyContainAlphanumericCharacters {
            get {
                return ResourceManager.GetString("AliasIsNotValidAliasCanOnlyContainAlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api key cannot be blank..
        /// </summary>
        public static string ApiKeyCannotBeBlank {
            get {
                return ResourceManager.GetString("ApiKeyCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative..
        /// </summary>
        public static string ArgumentCannotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative or zero..
        /// </summary>
        public static string ArgumentCannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null..
        /// </summary>
        public static string ArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null or empty..
        /// </summary>
        public static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate api key when api access is not allowed..
        /// </summary>
        public static string CannotGenerateApiKeyWhenApiAccessIsNotAllowed {
            get {
                return ResourceManager.GetString("CannotGenerateApiKeyWhenApiAccessIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink url for its own domain..
        /// </summary>
        public static string CannotShrinkUrlForItsOwnDomain {
            get {
                return ResourceManager.GetString("CannotShrinkUrlForItsOwnDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink url which matches with our banned domains..
        /// </summary>
        public static string CannotShrinkUrlWhichMatchesWithOurBannedDomains {
            get {
                return ResourceManager.GetString("CannotShrinkUrlWhichMatchesWithOurBannedDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the title.
        /// </summary>
        public static string CouldNotRetrieveTheTitle {
            get {
                return ResourceManager.GetString("CouldNotRetrieveTheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not in correct format..
        /// </summary>
        public static string EmailAddressIsNotInCorrectFormat {
            get {
                return ResourceManager.GetString("EmailAddressIsNotInCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression cannot be blank..
        /// </summary>
        public static string ExpressionCannotBeBlank {
            get {
                return ResourceManager.GetString("ExpressionCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid api key &quot;{0}&quot;..
        /// </summary>
        public static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid delegate reference type..
        /// </summary>
        public static string InvalidDelegateReferenceType {
            get {
                return ResourceManager.GetString("InvalidDelegateReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OpenID user name..
        /// </summary>
        public static string InvalidOpenIDUserName {
            get {
                return ResourceManager.GetString("InvalidOpenIDUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address cannot be blank..
        /// </summary>
        public static string IpAddressCannotBeBlank {
            get {
                return ResourceManager.GetString("IpAddressCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address is not in valid format..
        /// </summary>
        public static string IpAddressIsNotInValidFormat {
            get {
                return ResourceManager.GetString("IpAddressIsNotInValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of urls must be positive..
        /// </summary>
        public static string MaximumNumberOfUrlsMustBePositive {
            get {
                return ResourceManager.GetString("MaximumNumberOfUrlsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID user name cannot be blank..
        /// </summary>
        public static string OpenIDUserNameCannotBeBlank {
            get {
                return ResourceManager.GetString("OpenIDUserNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix cannot be blank..
        /// </summary>
        public static string PrefixCannotBeBlank {
            get {
                return ResourceManager.GetString("PrefixCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix must be an url..
        /// </summary>
        public static string PrefixMustBeAnUrl {
            get {
                return ResourceManager.GetString("PrefixMustBeAnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unholy going on!!!!.
        /// </summary>
        public static string SomethingUnholyGoingOn {
            get {
                return ResourceManager.GetString("SomethingUnholyGoingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias &quot;{0}&quot; already exists..
        /// </summary>
        public static string SpecifiedAliasAlreadyExists {
            get {
                return ResourceManager.GetString("SpecifiedAliasAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified alias is already used by another url..
        /// </summary>
        public static string SpecifiedAliasIsAlreadyUsedByAnotherUrl {
            get {
                return ResourceManager.GetString("SpecifiedAliasIsAlreadyUsedByAnotherUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; alias matches with our reserved alias. Please use a different alias..
        /// </summary>
        public static string SpecifiedAliasMatchesWithOurReservedAlias {
            get {
                return ResourceManager.GetString("SpecifiedAliasMatchesWithOurReservedAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &quot;{0}&quot; already exists..
        /// </summary>
        public static string SpecifiedExpressionAlreadyExists {
            get {
                return ResourceManager.GetString("SpecifiedExpressionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address &quot;{0}&quot; already exists..
        /// </summary>
        public static string SpecifiedIpAddressAlreadyExists {
            get {
                return ResourceManager.GetString("SpecifiedIpAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &quot;{0}&quot; already exists..
        /// </summary>
        public static string SpecifiedPrefixAlreadyExists {
            get {
                return ResourceManager.GetString("SpecifiedPrefixAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index cannot be negative..
        /// </summary>
        public static string StartIndexCannotBeNegative {
            get {
                return ResourceManager.GetString("StartIndexCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle the request..
        /// </summary>
        public static string UnableToHandleTheRequest {
            get {
                return ResourceManager.GetString("UnableToHandleTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login with your preferred OpenID provider..
        /// </summary>
        public static string UnableToLoginWithYourPreferredOpenIDProvider {
            get {
                return ResourceManager.GetString("UnableToLoginWithYourPreferredOpenIDProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url cannot be blank..
        /// </summary>
        public static string UrlCannotBeBlank {
            get {
                return ResourceManager.GetString("UrlCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is not in valid format..
        /// </summary>
        public static string UrlIsNotInValidFormat {
            get {
                return ResourceManager.GetString("UrlIsNotInValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url with the &quot;{0}&quot; alias does not exist..
        /// </summary>
        public static string UrlWithTheSpecifiedAliasDoesNotExist {
            get {
                return ResourceManager.GetString("UrlWithTheSpecifiedAliasDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; user does not exist..
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has already reached daily limit..
        /// </summary>
        public static string UserHasAlreadyReachedYourDailyLimit {
            get {
                return ResourceManager.GetString("UserHasAlreadyReachedYourDailyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; user is currently locked out..
        /// </summary>
        public static string UserIsCurrentlyLockedOut {
            get {
                return ResourceManager.GetString("UserIsCurrentlyLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to access with apiKey &quot;{0}&quot;..
        /// </summary>
        public static string UserIsNotAllowedToAccessWithSpecifiedApiKey {
            get {
                return ResourceManager.GetString("UserIsNotAllowedToAccessWithSpecifiedApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be blank..
        /// </summary>
        public static string UserNameCannotBeBlank {
            get {
                return ResourceManager.GetString("UserNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with &quot;{0}&quot; api key is currently locked out..
        /// </summary>
        public static string UserWithSpecifiedApiKeyIsLockedOut {
            get {
                return ResourceManager.GetString("UserWithSpecifiedApiKeyIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should not be null..
        /// </summary>
        public static string VariableCannotBeNull {
            get {
                return ResourceManager.GetString("VariableCannotBeNull", resourceCulture);
            }
        }
    }
}
